// ============= ENUMS Y TIPOS BASE =============

export type UserRole = 'ADMIN' | 'MANAGER' | 'CASHIER';

export type SaleType = 'WEIGHT' | 'UNIT';

export type CashSessionStatus = 'OPEN' | 'CLOSED';

export type SaleStatus = 'DRAFT' | 'COMPLETED' | 'CANCELLED';

export type PaymentMethod = 'CASH' | 'CARD' | 'TRANSFER' | 'MIXED';

export type MovementType = 
  | 'PURCHASE_IN' 
  | 'ADJUST_IN' 
  | 'ADJUST_OUT' 
  | 'WASTE' 
  | 'SALE_OUT' 
  | 'RETURN_IN';

export type CashMovementType = 'DEPOSIT' | 'WITHDRAWAL' | 'ADJUSTMENT';

export type OrderStatus = 'PENDING' | 'READY' | 'DELIVERED' | 'CANCELLED';

export type BarcodeType =
  | 'STANDARD'        // Código de barras estándar (EAN-13, UPC, etc.)
  | 'WEIGHT_EMBEDDED' // Código con peso embebido (6 dígitos del segmento W de balanza)
  | 'NONE';           // Sin código de barras (productos sin código)

// ============= INTERFACES =============

export interface User {
  id: string;
  role: UserRole;
  username: string;
  fullName: string;
  pin: string;
  isActive: boolean;
}

export interface UserResponse {
  id: string;
  username: string;
  fullName: string;
  role: UserRole;
  isActive: boolean;
}

export interface ProductCategory {
  id: string;
  name: string;
}

export interface Product {
  id: string;
  categoryId: string | null;
  sku: string; // Auto-generated by backend, read-only
  name: string;
  saleType: SaleType;
  unit: string;
  price: number;
  taxRate: number;
  isActive: boolean;
  isFavorite?: boolean; // Para el prototipo
  
  // Sistema de inventario
  barcodeType?: BarcodeType; // Required for real products, optional for mock data
  barcode?: string; // Required for real products - código de barras del producto
  barcodePrefix?: string; // Prefijo para identificar en scanner (ej: "20" para precios embebidos)
  
  // Control de stock (solo para UNIT_STOCK y UNIT_VARIABLE)
  stockUnits?: number;     // Stock disponible en unidades
  minStockAlert?: number;  // Alerta de stock mínimo
  
  // Para WEIGHT_MANUAL (referencia, no se controla stock)
  estimatedStockKg?: number; // Solo informativo
  
  // Descuentos (para impresión PLU y futuras funcionalidades)
  discountPrice?: number;   // Precio con descuento
  discountActive?: boolean; // Si el descuento está activo
}

export interface CashSession {
  id: string;
  terminalId: string;
  userId: string;
  status: CashSessionStatus;
  openedAt: string;
  openingAmount: number;
  openingNotes: string | null;
  closedAt: string | null;
  closingNotes: string | null;
  expectedAmount: number | null;
  closingAmount: number | null;
  differenceAmount: number | null;
  user?: {
    id: string;
    fullName: string;
    username?: string;
  };
  closedBy?: {
    id: string;
    fullName: string;
    username?: string;
  };
}

export interface CashMovement {
  id: string;
  cashSessionId: string;
  type: CashMovementType;
  amount: number;
  reason: string;
  createdBy: string;
  createdAt: string;
}

export interface SaleItem {
  id: string;
  productId: string;
  productName: string;
  saleType: SaleType;
  qty: number;
  unit: string; // 'kg', 'unid', 'lt', etc.
  unitPrice: number;
  discount: number;
  total: number;
  // Para productos de peso (WEIGHT, VACUUM_PACKED)
  actualWeight?: number; // Peso real (en kg)
  // Para productos de balanza escaneados
  scannedBarcode?: string; // Código completo de 18 dígitos de la etiqueta
  scannedSubtotal?: number; // Precio total fijo extraído de la etiqueta
}

export interface Sale {
  id: string;
  cashSessionId: string;
  cashierId: string; // userId en backend se llama cashierId
  status: SaleStatus;
  items: SaleItem[];
  subtotal: number;
  discount: number; // discountTotal → discount
  total: number;
  paymentMethod: PaymentMethod;
  cashAmount: number | null;
  cardAmount: number | null;
  transferAmount: number | null;
  changeAmount: number | null; // vuelto
  notes: string | null;
  customerName: string | null;
  orderId?: string;
  createdAt: string;
}

export interface InventoryBalance {
  id: string;
  productId: string;
  warehouseId: string;
  qty: number;
  updatedAt: string;
}

export interface InventoryMovement {
  id: string;
  type: MovementType;
  productId: string;
  warehouseId: string;
  qty: number;
  unitCost: number | null;
  referenceType: string | null;
  referenceId: string | null;
  reason: string | null;
  createdBy: string;
  createdAt: string;
}

export interface Terminal {
  id: string;
  name: string;
  location: string | null;
  isActive: boolean;
}

// ============= TIPOS PARA EL UI =============

export interface CartItem extends SaleItem {
  product: Product;
  originalUnitPrice?: number; // Precio original del sistema (antes del descuento)
  effectiveUnitPrice?: number; // Precio efectivo por unidad (después del descuento) - usado para cálculos proporcionales
  discountAutoDetected?: boolean; // Indica si el descuento fue detectado automáticamente por la balanza
}

export interface DailySummary {
  date: string;
  totalSales: number;
  totalAmount: number;
  cashAmount: number;
  transferAmount: number;
  cardAmount: number;
}

export interface ProductSalesSummary {
  productId: string;
  productName: string;
  totalQty: number;
  totalAmount: number;
  salesCount: number;
}

// ============= PEDIDOS/RESERVAS =============

export interface Customer {
  id: string;
  name?: string; // Optional if company is provided
  company?: string; // Optional if name is provided
  phone?: string;
  email?: string;
  address?: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Order {
  id: string;
  orderNumber: number; // Correlativo para fácil identificación
  customerId: string;
  customerName: string; // Snapshot para histórico
  customerPhone: string; // Snapshot
  status: OrderStatus;
  deliveryDate: string; // Fecha de entrega
  deliveryTime: string; // Hora de entrega (HH:mm)
  items: OrderItem[];
  subtotal: number;
  discount: number;
  total: number;
  notes?: string; // Notas del pedido
  createdBy: string; // Usuario que creó el pedido
  saleId?: string; // Link a la venta cuando se cobra el pedido
  deliveredBy?: string; // Usuario que entregó/cobró el pedido
  createdAt: string;
  updatedAt: string;
  completedAt?: string;
  cancelledAt?: string;
  cancellationReason?: string;
}

export interface OrderItem {
  id: string;
  orderId: string;
  productId: string;
  productName: string; // Snapshot
  productSku: string; // Snapshot
  saleType: SaleType;
  qty: number;
  unit: string;
  unitPrice: number;
  total: number;
  discount?: number; // Descuento aplicado al item
  notes?: string; // Notas específicas del item (ej: "corte fino", "sin grasa")
}
